### ISSUE TITLE
IP输入功能改进建议

### ISSUE THREAD

**Issue by jzz3933** [Jimmuy/N1_controler#1]
非常感谢做出这款遥控器，遥控器本身很好用
本人不是特别懂安卓编程，不知道下面建议实现起来是否复杂或可行，只是提一些改进想法：
1、能否在输入IP那里增加  搜索局域网内设备及其IP  的功能，输入IP的过程替换为直接点选N1盒子，这样可以更方便以及降低使用难度
2、能否增加目前连接的是哪个IP的指示，比如IP地址可以放在遥控器界面的最上方，这样可以知道到底是连着还是没连着。应用背景是：我个人是用华为P30 安卓10测试，偶尔会出现需要重新输入IP才能操控的情况（盒子没有断电，IP也没有变的情况）不知道到底是连上没连上，或其他原因
3、您给出的下载软件连接返回404
再次感谢您写的软件！！

**Comment by Jimmuy** [comment]
> 非常感谢做出这款遥控器，遥控器本身很好用
> 本人不是特别懂安卓编程，不知道下面建议实现起来是否复杂或可行，只是提一些改进想法：
> 1、能否在输入IP那里增加 搜索局域网内设备及其IP 的功能，输入IP的过程替换为直接点选N1盒子，这样可以更方便以及降低使用难度
> 2、能否增加目前连接的是哪个IP的指示，比如IP地址可以放在遥控器界面的最上方，这样可以知道到底是连着还是没连着。应用背景是：我个人是用华为P30 安卓10测试，偶尔会出现需要重新输入IP才能操控的情况（盒子没有断电，IP也没有变的情况）不知道到底是连上没连上，或其他原因
> 3、您给出的下载软件连接返回404
> 再次感谢您写的软件！！

收到，
1.好像无法获取局域网内所有的设备，所以这个功能不是很好实现（我去查一下，可以的话我会加一下这个功能）
2.bug收到，会考虑加一个显示当前IP的功能。
3.404是因为发布软件的服务商在紧急维护，估计过两天会恢复功能

**Comment by Jimmuy** [comment]
> 非常感谢做出这款遥控器，遥控器本身很好用
> 本人不是特别懂安卓编程，不知道下面建议实现起来是否复杂或可行，只是提一些改进想法：
> 1、能否在输入IP那里增加 搜索局域网内设备及其IP 的功能，输入IP的过程替换为直接点选N1盒子，这样可以更方便以及降低使用难度
> 2、能否增加目前连接的是哪个IP的指示，比如IP地址可以放在遥控器界面的最上方，这样可以知道到底是连着还是没连着。应用背景是：我个人是用华为P30 安卓10测试，偶尔会出现需要重新输入IP才能操控的情况（盒子没有断电，IP也没有变的情况）不知道到底是连上没连上，或其他原因
> 3、您给出的下载软件连接返回404
> 再次感谢您写的软件！！

ip功能已添加，项目根目录有新版本apk文件，你说的重新输入IP才生效的问题暂时没遇到，你先使用试试，欢迎继续反馈。

**Comment by jzz3933** [comment]
> > 非常感谢做出这款遥控器，遥控器本身很好用
> > 本人不是特别懂安卓编程，不知道下面建议实现起来是否复杂或可行，只是提一些改进想法：
> > 1、能否在输入IP那里增加 搜索局域网内设备及其IP 的功能，输入IP的过程替换为直接点选N1盒子，这样可以更方便以及降低使用难度
> > 2、能否增加目前连接的是哪个IP的指示，比如IP地址可以放在遥控器界面的最上方，这样可以知道到底是连着还是没连着。应用背景是：我个人是用华为P30 安卓10测试，偶尔会出现需要重新输入IP才能操控的情况（盒子没有断电，IP也没有变的情况）不知道到底是连上没连上，或其他原因
> > 3、您给出的下载软件连接返回404
> > 再次感谢您写的软件！！
> 
> ip功能已添加，项目根目录有新版本apk文件，你说的重新输入IP才生效的问题暂时没遇到，你先使用试试，欢迎继续反馈。

已下载试用，目前一切运行正常！感谢作者！
因为家里没有的N1盒子的实物遥控器，所以盒子的IP地址需要进入路由器管理界面才能获得，对于爸妈他们操作的学习成本稍高，所以如果能实现之前提到的第一条改进  **增加 搜索局域网内设备及其IP 的功能** 会非常棒！！无论如何，还是感谢作者！
